from abc import ABC, abstractmethod
from typing import List
from FactoryMethodZoo.IAnimal import IAnimal

class AnimalFactory(ABC):

    @abstractmethod
    def create_lion(self) -> IAnimal: ...
    @abstractmethod
    def create_elephant(self) -> IAnimal: ...
    @abstractmethod
    def create_penguin(self) -> IAnimal: ...
    @abstractmethod
    def create_white_bear(self) -> IAnimal: ...
    @abstractmethod
    def create_grizzly_bear(self) -> IAnimal: ...
    @abstractmethod
    def create_moose(self) -> IAnimal: ...

    @abstractmethod
    def create_all_animals(self) -> List[IAnimal]: ...