from abc import ABC, abstractmethod
from BuilderCustomer.CustomerProfile import CustomerProfile

class ICustomerBuilder(ABC):
    @abstractmethod
    def reset(self) -> None: ...
    @abstractmethod
    def add_first_name(self, name: str) -> None: ...
    @abstractmethod
    def add_middle_name(self, name: str) -> None: ...
    @abstractmethod
    def add_last_name(self, name: str) -> None: ...
    @abstractmethod
    def add_primary_email(self, email: str) -> None: ...
    @abstractmethod
    def add_secondary_email(self, email: str) -> None: ...
    @abstractmethod
    def add_primary_mobile(self, number: str) -> None: ...
    @abstractmethod
    def add_secondary_mobile(self, number: str) -> None: ...
    @abstractmethod
    def get_product(self) -> CustomerProfile: ...